### ISSUE TITLE
目测亚马逊投递出了问题

### ISSUE THREAD

**Issue by fbi007130** [jiedan/kindlereader#39]
5号后就再没投递成功，用回曾经投递成功的mobi文件去投递也显示失败，不知道为什么原因？其他人有遇上过吗？

**Comment by cerebellum92** [comment]
我也失败，而且之前虽然可以投递，不过却会被转成book 格式。估计是kindlereader做出来的mobi格式不被接受了。我已改用kindleear。目前没遇到太多问题，就是fullrss功能弱了些。

**Comment by cerebellum92** [comment]
补充一下，如果直接把做出来的档案放到kindle里是正常的。个人猜测是amazon那改了什么造成这个问题的。

**Comment by fbi007130** [comment]
目测恢复了
